version: '3.9'

services:

  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./code:/data/mysite.local/
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    image: php-fpm
    container_name: php
#    ports:
#      - "9000:9090"
    volumes:
      - ./code:/data/mysite.local/
    depends_on:
      - clickhouse
    networks:
      - app-network

  # Fluentd log collector
#  fluentd:
#    image: fluent/fluentd
#    volumes:
#      - ./docker/fluentd/fluentd.conf:/fluentd/etc/fluentd.conf
#    depends_on:
#      - clickhouse
#    networks:
#      - app-network

  # ClickHouse database
  clickhouse:
    image: yandex/clickhouse-server-no-simd
    container_name: clickhouse
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - app-network

  # Redash visualization tool
#  redash:
#    image: redash/redash
#    depends_on:
#      - clickhouse
#    ports:
#      - "5000:5000"
#    environment:
#      REDASH_DATABASE_URL: "clickhouse://clickhouse:8123"
#      REDASH_SECRET_KEY: "mysecretkey"
#      REDASH_COOKIE_SECRET: "mycookiesecret"
#      REDASH_WEB_WORKERS: "4"
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge