version: '3.9'

services:

  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    image: php-fpm
    container_name: php
#    ports:
#      - "9090:9000"
    volumes:
      - ./code:/data/mysite.local/
    depends_on:
      - clickhouse
    networks:
      - app-network

  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - app-network

  redash:
    image: redash/redash
    container_name: redash
    ports:
      - "5000:5000"
#    environment:
#      REDASH_DATABASE_URL: "clickhouse://clickhouse:8123"
#      REDASH_SECRET_KEY: "mysecretkey"
#      REDASH_COOKIE_SECRET: "mycookiesecret"
#      REDASH_WEB_WORKERS: "4"
    depends_on:
      - clickhouse
    networks:
      - app-network

networks:
  app-network:
    driver: bridge